// ============================================================
// 한자 데이터베이스 (이름용 대표 한자 300자+)
// 각 항목: { char, korean, strokes, element, meaning, gender }
// element: 木火土金水
// gender: M=남, F=여, N=중성
// ============================================================

const HANJA_DB = [
  // ── 木 (목) ──
  { char: "林", korean: "림", strokes: 8, element: "木", meaning: "수풀, 무성함", gender: "N" },
  { char: "樹", korean: "수", strokes: 16, element: "木", meaning: "나무, 심다", gender: "M" },
  { char: "植", korean: "식", strokes: 12, element: "木", meaning: "심다, 기르다", gender: "M" },
  { char: "根", korean: "근", strokes: 10, element: "木", meaning: "뿌리, 근본", gender: "M" },
  { char: "桂", korean: "계", strokes: 10, element: "木", meaning: "계수나무, 향기", gender: "F" },
  { char: "楠", korean: "남", strokes: 13, element: "木", meaning: "녹나무, 강인함", gender: "M" },
  { char: "梧", korean: "오", strokes: 11, element: "木", meaning: "오동나무, 품격", gender: "N" },
  { char: "棟", korean: "동", strokes: 12, element: "木", meaning: "마룻대, 기둥", gender: "M" },
  { char: "柳", korean: "류", strokes: 9, element: "木", meaning: "버드나무, 유연함", gender: "F" },
  { char: "松", korean: "송", strokes: 8, element: "木", meaning: "소나무, 절개", gender: "M" },
  { char: "森", korean: "삼", strokes: 12, element: "木", meaning: "울창한 숲", gender: "M" },
  { char: "枝", korean: "지", strokes: 8, element: "木", meaning: "가지, 뻗어나감", gender: "F" },
  { char: "桃", korean: "도", strokes: 10, element: "木", meaning: "복숭아, 아름다움", gender: "F" },
  { char: "梅", korean: "매", strokes: 11, element: "木", meaning: "매화, 굳은 절개", gender: "F" },
  { char: "竹", korean: "죽", strokes: 6, element: "木", meaning: "대나무, 곧음", gender: "M" },
  { char: "杰", korean: "걸", strokes: 8, element: "木", meaning: "뛰어난 인재", gender: "M" },
  { char: "木", korean: "목", strokes: 4, element: "木", meaning: "나무, 바탕", gender: "N" },
  { char: "東", korean: "동", strokes: 8, element: "木", meaning: "동쪽, 봄기운", gender: "M" },
  { char: "春", korean: "춘", strokes: 9, element: "木", meaning: "봄, 생명력", gender: "N" },
  { char: "茂", korean: "무", strokes: 8, element: "木", meaning: "무성하다, 번성", gender: "M" },
  { char: "葉", korean: "엽", strokes: 12, element: "木", meaning: "잎, 세대", gender: "N" },
  { char: "楓", korean: "풍", strokes: 13, element: "木", meaning: "단풍나무", gender: "N" },
  { char: "橋", korean: "교", strokes: 16, element: "木", meaning: "다리, 이어줌", gender: "N" },
  { char: "朴", korean: "박", strokes: 6, element: "木", meaning: "순박함, 통나무", gender: "N" },
  { char: "樂", korean: "락", strokes: 15, element: "木", meaning: "즐거움, 음악", gender: "N" },

  // ── 火 (화) ──
  { char: "炎", korean: "염", strokes: 8, element: "火", meaning: "불꽃, 뜨거운 열정", gender: "M" },
  { char: "明", korean: "명", strokes: 8, element: "火", meaning: "밝다, 총명함", gender: "N" },
  { char: "煜", korean: "욱", strokes: 13, element: "火", meaning: "불빛, 빛남", gender: "M" },
  { char: "熙", korean: "희", strokes: 13, element: "火", meaning: "빛나다, 화평함", gender: "N" },
  { char: "燦", korean: "찬", strokes: 17, element: "火", meaning: "눈부시게 빛남, 찬란함", gender: "M" }, // 중성적 의미를 결합하여 하나로 유지
  { char: "炫", korean: "현", strokes: 9, element: "火", meaning: "빛나다, 눈부심", gender: "M" },
  { char: "烈", korean: "열", strokes: 10, element: "火", meaning: "세차다, 강렬함", gender: "M" },
  { char: "燁", korean: "엽", strokes: 16, element: "火", meaning: "불빛이 빛남", gender: "M" },
  { char: "灿", korean: "찬", strokes: 7, element: "火", meaning: "빛나다", gender: "M" },
  { char: "南", korean: "남", strokes: 9, element: "火", meaning: "남쪽, 따뜻함", gender: "N" },
  { char: "夏", korean: "하", strokes: 10, element: "火", meaning: "여름, 크고 화려함", gender: "N" },
  { char: "光", korean: "광", strokes: 6, element: "火", meaning: "빛, 영광", gender: "M" },
  { char: "曜", korean: "요", strokes: 18, element: "火", meaning: "빛나다, 요일", gender: "N" },
  { char: "炳", korean: "병", strokes: 9, element: "火", meaning: "밝게 빛나다", gender: "M" },
  { char: "輝", korean: "휘", strokes: 15, element: "火", meaning: "빛나다, 찬란함", gender: "M" },
  { char: "照", korean: "조", strokes: 13, element: "火", meaning: "비추다, 밝히다", gender: "N" },
  { char: "赫", korean: "혁", strokes: 14, element: "火", meaning: "빛나다, 위엄", gender: "M" },
  { char: "日", korean: "일", strokes: 4, element: "火", meaning: "해, 날", gender: "M" },
  { char: "星", korean: "성", strokes: 9, element: "火", meaning: "별, 빛남", gender: "N" },
  { char: "熱", korean: "열", strokes: 15, element: "火", meaning: "뜨겁다, 열정", gender: "M" },
  { char: "灼", korean: "작", strokes: 7, element: "火", meaning: "불사르다, 빛나다", gender: "M" },
  { char: "暉", korean: "휘", strokes: 13, element: "火", meaning: "햇빛, 빛나다", gender: "N" },

  // ── 土 (토) ──
  { char: "培", korean: "배", strokes: 11, element: "土", meaning: "기르다, 북돋움", gender: "N" },
  { char: "基", korean: "기", strokes: 11, element: "土", meaning: "기초, 근본", gender: "M" },
  { char: "坤", korean: "곤", strokes: 8, element: "土", meaning: "땅, 대지의 덕", gender: "F" },
  { char: "垠", korean: "은", strokes: 9, element: "土", meaning: "땅의 끝, 경계", gender: "N" },
  { char: "城", korean: "성", strokes: 9, element: "土", meaning: "성, 굳건함", gender: "M" },
  { char: "堅", korean: "견", strokes: 11, element: "土", meaning: "굳다, 단단함", gender: "M" },
  { char: "土", korean: "토", strokes: 3, element: "土", meaning: "흙, 대지", gender: "N" },
  { char: "中", korean: "중", strokes: 4, element: "土", meaning: "가운데, 중심", gender: "N" },
  { char: "厚", korean: "후", strokes: 9, element: "土", meaning: "두텁다, 도타움", gender: "M" },
  { char: "重", korean: "중", strokes: 9, element: "土", meaning: "무겁다, 중요함", gender: "M" },
  { char: "誠", korean: "성", strokes: 14, element: "土", meaning: "정성, 진실됨", gender: "N" },
  { char: "信", korean: "신", strokes: 9, element: "土", meaning: "믿음, 신의", gender: "N" },
  { char: "仁", korean: "인", strokes: 4, element: "土", meaning: "어질다, 사랑", gender: "N" },
  { char: "義", korean: "의", strokes: 13, element: "土", meaning: "의로움, 올바름", gender: "N" },
  { char: "德", korean: "덕", strokes: 15, element: "土", meaning: "덕, 은혜", gender: "N" },
  { char: "博", korean: "박", strokes: 12, element: "土", meaning: "넓다, 박식함", gender: "M" },
  { char: "寬", korean: "관", strokes: 15, element: "土", meaning: "너그럽다, 넓음", gender: "N" },
  { char: "安", korean: "안", strokes: 6, element: "土", meaning: "편안함, 안정", gender: "N" },
  { char: "泰", korean: "태", strokes: 10, element: "土", meaning: "크고 편안함", gender: "N" },
  { char: "壯", korean: "장", strokes: 7, element: "土", meaning: "씩씩하다, 강건", gender: "M" },
  { char: "固", korean: "고", strokes: 8, element: "土", meaning: "굳다, 단단함", gender: "M" },
  { char: "埈", korean: "준", strokes: 10, element: "土", meaning: "높고 험준하다", gender: "M" },
  { char: "垣", korean: "원", strokes: 9, element: "土", meaning: "담, 울타리", gender: "N" },

  // ── 金 (금) ──
  { char: "鎭", korean: "진", strokes: 18, element: "金", meaning: "진정시키다, 안정", gender: "M" },
  { char: "鉉", korean: "현", strokes: 13, element: "金", meaning: "솥귀, 현악기줄", gender: "M" },
  { char: "鑫", korean: "흠", strokes: 24, element: "金", meaning: "쇠붙이의 빛, 재물", gender: "M" },
  { char: "銀", korean: "은", strokes: 14, element: "金", meaning: "은, 순수함", gender: "F" },
  { char: "錦", korean: "금", strokes: 16, element: "金", meaning: "비단, 화려함", gender: "F" },
  { char: "金", korean: "금", strokes: 8, element: "金", meaning: "금, 귀중함", gender: "N" },
  { char: "鐵", korean: "철", strokes: 21, element: "金", meaning: "쇠, 굳건함", gender: "M" },
  { char: "鋒", korean: "봉", strokes: 15, element: "金", meaning: "날카로운 끝", gender: "M" },
  { char: "剛", korean: "강", strokes: 10, element: "金", meaning: "굳세다, 강인함", gender: "M" },
  { char: "鍾", korean: "종", strokes: 17, element: "金", meaning: "종, 모으다", gender: "M" },
  { char: "銓", korean: "전", strokes: 14, element: "金", meaning: "저울질, 선발", gender: "M" },
  { char: "鈺", korean: "옥", strokes: 13, element: "金", meaning: "보옥, 보배", gender: "F" },
  { char: "鋭", korean: "예", strokes: 15, element: "金", meaning: "날카롭다, 예리함", gender: "M" },
  { char: "西", korean: "서", strokes: 6, element: "金", meaning: "서쪽, 가을기운", gender: "N" },
  { char: "秋", korean: "추", strokes: 9, element: "金", meaning: "가을, 성숙함", gender: "N" },
  { char: "勇", korean: "용", strokes: 9, element: "金", meaning: "용감함, 씩씩함", gender: "M" },
  { char: "鉦", korean: "정", strokes: 13, element: "金", meaning: "징, 아름다운 소리", gender: "N" },
  { char: "鏡", korean: "경", strokes: 19, element: "金", meaning: "거울, 밝음", gender: "N" },
  { char: "銳", korean: "예", strokes: 15, element: "金", meaning: "날카롭다", gender: "M" },
  { char: "鈞", korean: "균", strokes: 12, element: "金", meaning: "균형, 공평함", gender: "N" },
  { char: "鎬", korean: "호", strokes: 18, element: "金", meaning: "호경, 빛남", gender: "M" },

  // ── 水 (수) ──
  { char: "泳", korean: "영", strokes: 8, element: "水", meaning: "헤엄치다, 진취", gender: "N" },
  { char: "澤", korean: "택", strokes: 16, element: "水", meaning: "연못, 은혜로움", gender: "M" },
  { char: "洙", korean: "수", strokes: 9, element: "水", meaning: "물가, 맑음", gender: "M" },
  { char: "浩", korean: "호", strokes: 10, element: "水", meaning: "넓고 큰 물, 크다", gender: "M" },
  { char: "汎", korean: "범", strokes: 6, element: "水", meaning: "넓다, 두루 미침", gender: "M" },
  { char: "淸", korean: "청", strokes: 11, element: "水", meaning: "맑다, 깨끗함", gender: "N" },
  { char: "河", korean: "하", strokes: 8, element: "水", meaning: "강, 흐름", gender: "N" },
  { char: "海", korean: "해", strokes: 10, element: "水", meaning: "바다, 넓음", gender: "N" },
  { char: "潤", korean: "윤", strokes: 15, element: "水", meaning: "윤택하다, 적심", gender: "N" },
  { char: "源", korean: "원", strokes: 13, element: "水", meaning: "근원, 원천", gender: "M" },
  { char: "波", korean: "파", strokes: 8, element: "水", meaning: "물결, 퍼짐", gender: "N" },
  { char: "湖", korean: "호", strokes: 12, element: "水", meaning: "호수, 넓음", gender: "N" },
  { char: "水", korean: "수", strokes: 4, element: "水", meaning: "물, 지혜", gender: "N" },
  { char: "北", korean: "북", strokes: 5, element: "水", meaning: "북쪽, 겨울기운", gender: "N" },
  { char: "冬", korean: "동", strokes: 5, element: "水", meaning: "겨울, 깊이 저축", gender: "N" },
  { char: "智", korean: "지", strokes: 12, element: "水", meaning: "지혜, 슬기로움", gender: "N" },
  { char: "涓", korean: "연", strokes: 10, element: "水", meaning: "가는 물줄기, 맑음", gender: "F" },
  { char: "漢", korean: "한", strokes: 14, element: "水", meaning: "한수, 웅장함", gender: "M" },
  { char: "淵", korean: "연", strokes: 11, element: "水", meaning: "깊은 못, 깊이", gender: "N" },
  { char: "泰", korean: "태", strokes: 10, element: "水", meaning: "크다, 편안함", gender: "N" },
  { char: "洋", korean: "양", strokes: 9, element: "水", meaning: "넓은 바다", gender: "N" },
  { char: "滿", korean: "만", strokes: 14, element: "水", meaning: "가득하다, 충만", gender: "N" },
  { char: "濟", korean: "제", strokes: 17, element: "水", meaning: "건너다, 구제", gender: "M" },
  { char: "浚", korean: "준", strokes: 10, element: "水", meaning: "깊다, 물을 파냄", gender: "M" },
  { char: "洛", korean: "락", strokes: 9, element: "水", meaning: "낙수, 편안함", gender: "N" },

  // ── 중성 / 자주 쓰이는 추가 한자 ──
  { char: "俊", korean: "준", strokes: 9, element: "水", meaning: "준걸, 뛰어남", gender: "M" },
  { char: "賢", korean: "현", strokes: 15, element: "土", meaning: "어질고 현명함", gender: "N" },
  { char: "雅", korean: "아", strokes: 12, element: "金", meaning: "우아함, 고상함", gender: "F" },
  { char: "娜", korean: "나", strokes: 10, element: "木", meaning: "아름다운 여자", gender: "F" },
  { char: "珍", korean: "진", strokes: 9, element: "金", meaning: "보배, 귀중함", gender: "N" },
  { char: "珠", korean: "주", strokes: 10, element: "金", meaning: "구슬, 보배", gender: "F" },
  { char: "琴", korean: "금", strokes: 12, element: "金", meaning: "거문고, 음악", gender: "F" },
  { char: "瑞", korean: "서", strokes: 13, element: "金", meaning: "상서로움, 좋은 징조", gender: "N" },
  { char: "玲", korean: "령", strokes: 9, element: "金", meaning: "옥이 울리는 소리", gender: "F" },
  { char: "璃", korean: "리", strokes: 15, element: "金", meaning: "유리, 투명함", gender: "F" },
  { char: "妍", korean: "연", strokes: 7, element: "木", meaning: "아름답다, 곱다", gender: "F" },
  { char: "芸", korean: "운", strokes: 7, element: "木", meaning: "향기로운 풀", gender: "F" },
  { char: "蓮", korean: "련", strokes: 13, element: "水", meaning: "연꽃, 청순함", gender: "F" },
  { char: "란", korean: "란", strokes: 19, element: "木", meaning: "난초, 향기로움", gender: "F" },
  { char: "花", korean: "화", strokes: 7, element: "木", meaning: "꽃, 아름다움", gender: "F" },
  { char: "秀", korean: "수", strokes: 7, element: "木", meaning: "빼어나다, 뛰어남", gender: "N" },
  { char: "英", korean: "영", strokes: 8, element: "木", meaning: "꽃부리, 뛰어남", gender: "N" },
  { char: "豪", korean: "호", strokes: 14, element: "水", meaning: "호걸, 호방함", gender: "M" },
  { char: "勝", korean: "승", strokes: 12, element: "火", meaning: "이기다, 뛰어남", gender: "M" },
  { char: "健", korean: "건", strokes: 11, element: "土", meaning: "건강하다, 씩씩함", gender: "M" },
  { char: "強", korean: "강", strokes: 11, element: "金", meaning: "강하다, 굳셈", gender: "M" },
  { char: "大", korean: "대", strokes: 3, element: "土", meaning: "크다, 위대함", gender: "M" },
  { char: "偉", korean: "위", strokes: 11, element: "土", meaning: "위대하다, 훌륭함", gender: "M" },
  { char: "才", korean: "재", strokes: 3, element: "木", meaning: "재능, 재주", gender: "N" },
  { char: "哲", korean: "철", strokes: 10, element: "水", meaning: "밝다, 지혜로움", gender: "M" },
  { char: "道", korean: "도", strokes: 12, element: "土", meaning: "길, 도리", gender: "N" },
  { char: "永", korean: "영", strokes: 5, element: "水", meaning: "길다, 영원함", gender: "N" },
  { char: "昊", korean: "호", strokes: 8, element: "火", meaning: "넓은 하늘, 광활함", gender: "M" },
  { char: "宇", korean: "우", strokes: 6, element: "土", meaning: "하늘, 우주", gender: "M" },
  { char: "宙", korean: "주", strokes: 8, element: "土", meaning: "우주, 영원", gender: "M" },
  { char: "翔", korean: "상", strokes: 12, element: "火", meaning: "날다, 비상함", gender: "M" },
  { char: "鶴", korean: "학", strokes: 21, element: "火", meaning: "학, 고고함", gender: "N" },
  { char: "鳳", korean: "봉", strokes: 14, element: "火", meaning: "봉황, 고귀함", gender: "N" },
  { char: "龍", korean: "용", strokes: 16, element: "水", meaning: "용, 으뜸", gender: "M" },
  { char: "虎", korean: "호", strokes: 8, element: "金", meaning: "호랑이, 위엄", gender: "M" },
  { char: "麒", korean: "기", strokes: 19, element: "土", meaning: "기린, 상서로움", gender: "M" },
  { char: "麟", korean: "린", strokes: 23, element: "土", meaning: "기린, 상서로운 동물", gender: "N" },
  { char: "慧", korean: "혜", strokes: 15, element: "火", meaning: "슬기롭다, 총명", gender: "F" },
  { char: "聰", korean: "총", strokes: 17, element: "金", meaning: "총명하다, 귀 밝음", gender: "N" },
  { char: "靈", korean: "령", strokes: 24, element: "火", meaning: "신령, 신비함", gender: "N" },
  { char: "藝", korean: "예", strokes: 18, element: "木", meaning: "예술, 재주", gender: "N" },
  { char: "文", korean: "문", strokes: 4, element: "木", meaning: "글, 문화", gender: "N" },
  { char: "武", korean: "무", strokes: 8, element: "金", meaning: "무예, 용맹", gender: "M" },
  { char: "學", korean: "학", strokes: 16, element: "水", meaning: "배움, 학문", gender: "N" },
  { char: "志", korean: "지", strokes: 7, element: "火", meaning: "뜻, 의지", gender: "N" },
  { char: "願", korean: "원", strokes: 19, element: "水", meaning: "바라다, 소원", gender: "N" },
  { char: "夢", korean: "몽", strokes: 13, element: "木", meaning: "꿈, 이상", gender: "N" },
  { char: "希", korean: "희", strokes: 7, element: "火", meaning: "바라다, 희망", gender: "N" },
  { char: "幸", korean: "행", strokes: 8, element: "火", meaning: "행복, 다행", gender: "N" },
  { char: "福", korean: "복", strokes: 13, element: "土", meaning: "복, 행운", gender: "N" },
  { char: "喜", korean: "희", strokes: 12, element: "火", meaning: "기쁨, 즐거움", gender: "N" },
  { char: "美", korean: "미", strokes: 9, element: "火", meaning: "아름답다, 선함", gender: "F" },
  { char: "善", korean: "선", strokes: 12, element: "土", meaning: "선하다, 착함", gender: "N" },
  { char: "和", korean: "화", strokes: 8, element: "土", meaning: "화목함, 조화", gender: "N" },
  { char: "平", korean: "평", strokes: 5, element: "土", meaning: "평화, 평온함", gender: "N" },
  { char: "貞", korean: "정", strokes: 9, element: "土", meaning: "곧다, 굳은 절개", gender: "F" },
  { char: "淑", korean: "숙", strokes: 11, element: "水", meaning: "맑다, 정숙함", gender: "F" },
  { char: "婉", korean: "완", strokes: 11, element: "土", meaning: "부드럽다, 유순함", gender: "F" },
  { char: "姿", korean: "자", strokes: 9, element: "金", meaning: "모습, 자태", gender: "F" },
  { char: "若", korean: "약", strokes: 8, element: "木", meaning: "같다, 부드러움", gender: "F" },
  { char: "靜", korean: "정", strokes: 16, element: "金", meaning: "고요하다, 청정함", gender: "F" },
  { char: "雪", korean: "설", strokes: 11, element: "水", meaning: "눈, 순결함", gender: "F" },
  { char: "月", korean: "월", strokes: 4, element: "水", meaning: "달, 아름다움", gender: "F" },
  { char: "朝", korean: "조", strokes: 12, element: "木", meaning: "아침, 새벽", gender: "N" },
  { char: "曉", korean: "효", strokes: 16, element: "火", meaning: "새벽, 밝아옴", gender: "N" },
  { char: "晨", korean: "신", strokes: 11, element: "火", meaning: "새벽, 아침별", gender: "N" },
  { char: "昇", korean: "승", strokes: 8, element: "火", meaning: "오르다, 상승", gender: "M" },
  { char: "旭", korean: "욱", strokes: 6, element: "火", meaning: "아침 해, 빛남", gender: "M" },
  { char: "晙", korean: "준", strokes: 10, element: "火", meaning: "밝다, 빛남", gender: "M" },
  { char: "燿", korean: "요", strokes: 18, element: "火", meaning: "빛나다, 광채", gender: "N" },
  { char: "峰", korean: "봉", strokes: 10, element: "土", meaning: "봉우리, 높음", gender: "M" },
  { char: "峻", korean: "준", strokes: 10, element: "土", meaning: "높고 험하다, 준엄", gender: "M" },
  { char: "嶺", korean: "령", strokes: 17, element: "土", meaning: "고갯마루, 높음", gender: "M" },
  { char: "巖", korean: "암", strokes: 23, element: "土", meaning: "바위, 굳건함", gender: "M" },
  { char: "山", korean: "산", strokes: 3, element: "土", meaning: "산, 의지함", gender: "N" },
  { char: "岳", korean: "악", strokes: 8, element: "土", meaning: "큰 산, 웅장함", gender: "M" },
];
if (typeof window !== 'undefined') window.HANJA_DB = HANJA_DB;
